[build]
  command = "npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_BASE_URL = "https://daycare-vg2j.onrender.com"

[[redirects]]
  from = "/uploads/*"
  to = "https://daycare-vg2j.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

